apiVersion: apps/v1
kind: Deployment
metadata:
  name: adi-bms-app
  namespace: adi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: adi-bms-container
        image: adi0901/bms:latest  
        ports:
        - containerPort: 3000  
